In [1]:
pip install dash==1.18.1

Note: you may need to restart the kernel to use updated packages.


'C:\Users\skama\anaconda3\Anaconda' is not recognized as an internal or external command,
operable program or batch file.


In [2]:
import numpy as np
mylist=[1,2,3,4,5]
array=np.array(mylist)

In [3]:
type(array)

numpy.ndarray

In [4]:
a=np.arange(0,10,2)

In [5]:
a

array([0, 2, 4, 6, 8])

In [6]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
array2=np.random.randint(0,100,(5,5))

In [8]:
array2

array([[51, 73, 81, 99, 60],
       [75, 76, 59, 69, 79],
       [96, 30, 99, 95, 97],
       [71,  7, 39, 68,  5],
       [ 2, 44, 59, 14,  8]])

In [9]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [10]:
np.random.seed(101)

In [11]:
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [12]:
array2.max()

99

In [13]:
array.argmax()

4

In [14]:
pip install plotly

Note: you may need to restart the kernel to use updated packages.


'C:\Users\skama\anaconda3\Anaconda' is not recognized as an internal or external command,
operable program or batch file.


In [15]:
import plotly.offline as pyo
import plotly.graph_objs as go

In [16]:
np.random.seed(42)

In [17]:
random_x=np.random.randint(1,101,100)
random_y=np.random.randint(1,101,100)
data=[go.Scatter(x=random_x,y=random_y,mode="markers",marker=dict(size=12,color="rgb(51,123,153)",symbol="pentagon",line={"width":2}))]
layout=go.Layout(title="Scatter Plot",xaxis={"title":"X-Axis"},yaxis=dict(title="Y-Axis"),hovermode="closest")
figure=go.Figure(data=data,layout=layout)


pyo.plot(figure)

'temp-plot.html'

In [18]:
np.random.seed(56)

In [19]:
random_x=np.linspace(0,1,100)
random_y=np.random.randn(100)
trace0=go.Scatter(x=random_x,y=random_y+5,mode="markers",name="markers")
trace1=go.Scatter(x=random_x,y=random_y,mode="lines",name="mylines")
trace2=go.Scatter(x=random_x,y=random_y,mode="lines+markers",name="mylines")
data=[trace0,trace1,trace2]
layout=go.Layout(title="LineChart")
figure=go.Figure(data=data,layout=layout)


pyo.plot(figure)

'temp-plot.html'

In [20]:
import pandas as pd
df=pd.read_csv("nst-est2017-alldata.csv")

In [21]:
df1=df[df["DIVISION"]=="1"]
df1.set_index("NAME",inplace=True)

In [22]:
cols=[col for col in df1.columns if col.startswith("POP")]
df1=df1[cols]

In [23]:
df1.head()

POPESTIMATE2010  POPESTIMATE2011  POPESTIMATE2012  \
NAME                                                               
Connecticut          3580171.0        3591927.0        3597705.0   
Maine                1327568.0        1327968.0        1328101.0   
Massachusetts        6564943.0        6612178.0        6659627.0   
New Hampshire        1316700.0        1318345.0        1320923.0   
Rhode Island         1053169.0        1052154.0        1052761.0   

               POPESTIMATE2013  POPESTIMATE2014  POPESTIMATE2015  \
NAME                                                               
Connecticut          3602470.0        3600188.0        3593862.0   
Maine                1327975.0        1328903.0        1327787.0   
Massachusetts        6711138.0        6757925.0        6794002.0   
New Hampshire        1322622.0        1328684.0        1330134.0   
Rhode Island         1052784.0        1054782.0        1055916.0   

               POPESTIMATE2016  POPESTIMATE2017  
NAME                                             
Connecticut          3587685.0        3588184.0  
Maine                1330232.0        1335907.0  
Massachusetts        6823721.0        6859819.0  
New Hampshire        1335015.0        1342795.0  
Rhode Island         1057566.0        1059639.0

In [25]:
data=[go.Scatter(x=df1.columns,y=df1.loc[name],mode="lines",name=name) for name in df1.index]
pyo.plot(data)

'temp-plot.html'

In [26]:
yuma=pd.read_csv("2010YumaAZ.csv")

In [27]:
yuma.head(5)

LST_DATE      DAY LST_TIME  T_HR_AVG
0  20100601  TUESDAY     0:00      25.2
1  20100601  TUESDAY     1:00      24.1
2  20100601  TUESDAY     2:00      24.4
3  20100601  TUESDAY     3:00      24.9
4  20100601  TUESDAY     4:00      22.8

In [32]:
day=yuma["DAY"].unique()
day

array(['TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY',
       'MONDAY'], dtype=object)

In [34]:
data=[]

In [39]:
for x in day:
        trace=go.Scatter(x=yuma["LST_TIME"],y=yuma[yuma["DAY"]==x]["T_HR_AVG"],mode="lines",name=x)
        data.append(trace)

In [40]:
layout=go.Layout(title="Temperature Avaerage")
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [41]:
medals=pd.read_csv("2018WinterOlympics.csv")

In [55]:
trace1=go.Bar(x=medals["NOC"],y=medals["Gold"],name="Gold",marker={"color":"#FFD700"})
trace2=go.Bar(x=medals["NOC"],y=medals["Silver"],name="Silver",marker={"color":"#9EA0A1"})
trace3=go.Bar(x=medals["NOC"],y=medals["Bronze"],name="Bronze",marker={"color":"#CD7F32"})
data=[trace1,trace2,trace3]
layout=go.Layout(title="Bar Chart",barmode="stack")
figure=go.Figure(data=data,layout=layout)
pyo.plot(figure)

'temp-plot.html'

In [56]:
surevy=pd.read_csv("mocksurvey.csv")

In [57]:
surevy.head(5)

Unnamed: 0  Strongly Agree  Somewhat Agree  Neutral  Somewhat Disagree  \
0  Question 1            0.45            0.25     0.10               0.12   
1  Question 2            0.12            0.07     0.48               0.18   
2  Question 3            0.05            0.22     0.19               0.23   

   Strongly Disagree  
0               0.08  
1               0.15  
2               0.31

In [62]:
trace1=[go.Bar(x=surevy.index,y=surevy[x],name=x) for x in surevy.columns ]
layout=go.Layout(title="Bar Chart",barmode="stack")
figure=go.Figure(data=trace1,layout=layout)
pyo.plot(figure)

'temp-plot.html'

In [63]:
df=pd.read_csv("mpg.csv")

In [72]:
data=[go.Scatter(x=df["horsepower"],y=df["mpg"],text=df["name"],mode="markers",marker=dict(size=df["weight"]/100,color=df["cylinders"],showscale=True))]
layout=go.Layout(title="Bubblechart")
figure=go.Figure(data=data,layout=layout)
pyo.plot(figure)

'temp-plot.html'

In [73]:
data=[go.Scatter(x=df["displacement"],y=df["acceleration"],text=df["name"],mode="markers",marker=dict(size=df["weight"]/400,color=df["cylinders"],showscale=True))]
layout=go.Layout(title="Bubblechart",hovermode='closest')
figure=go.Figure(data=data,layout=layout)
pyo.plot(figure)

'temp-plot.html'

In [83]:
y = [1,14,14,15,16,18,18,19,19,20,20,23,24,26,27,27,28,29,33,54]
data=[go.Box(y=y,boxpoints="outliers",jitter=0.3,pointpos=2.0)]
layout=go.Layout(title="Boxplot")
figure=go.Figure(data=data,layout=layout)
pyo.plot(figure)

'temp-plot.html'

In [84]:
snodgrass = [.209,.205,.196,.210,.202,.207,.224,.223,.220,.201]
twain = [.225,.262,.217,.240,.230,.229,.235,.217]
data=[go.Box(y=snodgrass,boxpoints="outliers",name="snodgrass"),go.Box(y=twain,boxpoints="outliers",name="twain")]
layout=go.Layout(title="Boxplot")
figure=go.Figure(data=data,layout=layout)
pyo.plot(figure)

'temp-plot.html'

In [85]:
df=pd.read_csv("abalone.csv")

In [86]:
df.head(5)

sex  length  diameter  height  whole_weight  shucked_weight  viscera_weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   shell_weight  rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7

In [90]:
x=np.random.choice(df["rings"],20,replace=False)
y=np.random.choice(df["rings"],30,replace=False)

In [91]:
data=[go.Box(y=x,boxpoints="outliers",name="Y"),go.Box(y=y,boxpoints="outliers",name="x")]
layout=go.Layout(title="Boxplot")
figure=go.Figure(data=data,layout=layout)
pyo.plot(figure)

'temp-plot.html'

In [4]:
!pip install dash
!pip install dash-renderer
!pip install dash_core_components
!pip install dash_html_components

  Stored in directory: C:\Users\skama\AppData\Local\pip\Cache\wheels\eb\56\fb\79b2169ce9fcb79753ec57a16abb8f0b7750b4c63d7eb3cea9
  Stored in directory: C:\Users\skama\AppData\Local\pip\Cache\wheels\cf\2b\5f\0928a6d1b7ebf280f21a2e925f36d662e6ba83e00b82c6b6bf
  Stored in directory: C:\Users\skama\AppData\Local\pip\Cache\wheels\e3\20\48\9022e1f2cb2fed4d9925370d0e17cbb3ab1164f3742d9b5e5a
  Stored in directory: C:\Users\skama\AppData\Local\pip\Cache\wheels\8d\01\46\78e4de185a8a4a2da8ba31da16c52170f036d4cebeeb6e07a2
  Stored in directory: C:\Users\skama\AppData\Local\pip\Cache\wheels\53\a0\0e\1105943524ee7060c5c45a22e45c77777a3d8801f2fe49e445
Successfully built dash dash-renderer dash-core-components dash-html-components dash-table


In [6]:
import dash
import dash_core_components as dcc
import dash_html_components as html

In [7]:
app=dash.Dash()


In [ ]:
app.layout=html.Div(children=[html.H1("Hello Dash!"),
                              html.Div("Dash:Web Applications with Python" ),
                              dcc.Graph(id="example",figure=
                              {"data":[{"x":[1,2,3,4,5],"y":[1,2,3,4,5],"type":"bar","name":"SF"},
                              {"x":[1,2,3,4,5],"y":[1,4,6,8,5],"type":"bar","name":"SF"}],"layout":{"title":"Bar Plot"}})])
if __name__ == "__main__":
    app.run_server()

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [07/Jan/2021 19:50:42] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [07/Jan/2021 19:50:42] "GET /_dash-component-suites/dash_renderer/polyfill@7.v1_8_3m1610035684.8.7.min.js HTTP/1.1" 200 -
127.0.0.1 - - [07/Jan/2021 19:50:42] "GET /_dash-component-suites/dash_renderer/react@16.v1_8_3m1610035684.14.0.min.js HTTP/1.1" 200 -
127.0.0.1 - - [07/Jan/2021 19:50:43] "GET /_dash-component-suites/dash_renderer/react-dom@16.v1_8_3m1610035684.14.0.min.js HTTP/1.1" 200 -
127.0.0.1 - - [07/Jan/2021 19:50:43] "GET /_dash-component-suites/dash_renderer/prop-types@15.v1_8_3m1610035684.7.2.min.js HTTP/1.1" 200 -
127.0.0.1 - - [07/Jan/2021 19:50:43] "GET /_dash-component-suites/dash_html_components/dash_html_components.v1_1_1m1610035813.min.js HTTP/1.1" 200 -
127.0.0.1 - - [07/Jan/2021 19:50:43] "GET /_dash-component-suites/dash_core_components/dash_core_components.v1_14_1m1610035736.min.js HTTP/1.1" 200 -
127.0.0.1 - - [07/Jan/2021 19:50